const {test}=require('node:test');const assert=require('node:assert/strict');
test('blue indicator is click-through, reused and automatically hidden',async()=>{
 const {agentIndicator}=await import('./target-manager.js');const vm=require('node:vm');let host,created=0,hide;
 const badge={};const context={document:{getElementById:()=>host,createElement:()=>{created++;return {style:{setProperty(name,value){this[name]=value}},setAttribute(){},attachShadow(){this.root={querySelector:()=>badge};return this.root}}},documentElement:{append:e=>host=e}},clearTimeout(){},setTimeout:fn=>{hide=fn;return 1}};
 vm.runInNewContext('('+agentIndicator.toString()+')("OBSERVING")',context);assert.match(host.root.innerHTML,/pointer-events:none!important/);assert.equal(host.style.display,'block');assert.equal(badge.textContent,'GPT Agent · OBSERVING');
 vm.runInNewContext('('+agentIndicator.toString()+')("WAITING")',context);assert.equal(created,1);hide();assert.equal(host.style.display,'none');
});
async function fixture(){const {TargetManager}=await import('./target-manager.js');let n=0;const local={},session={};const tabs=new Map([[11,{id:11,windowId:1,url:'https://one.test/',title:'One',active:true}],[22,{id:22,windowId:2,url:'https://two.test/',title:'Two',active:false}]]);const store=data=>({async get(){return structuredClone(data)},async set(value){Object.assign(data,structuredClone(value))}});const api={storage:{local:store(local),session:store(session)},tabs:{async query(){return [...tabs.values()]},async get(id){if(!tabs.has(id))throw Error('closed');return {...tabs.get(id)}},async update(id,value){Object.assign(tabs.get(id),value);return tabs.get(id)}},windows:{async update(){}}};return {manager:new TargetManager(api,{uuid:()=>String(++n)}),api,local,session,tabs,TargetManager};}
test('multiple targets retain independent identities when active tab changes',async()=>{const f=await fixture();const [a,b]=await Promise.all([f.manager.add({tabId:11,role:'GitHub'}),f.manager.add({tabId:22,role:'Docs'})]);f.tabs.get(11).active=false;f.tabs.get(22).active=true;assert.equal((await f.manager.resolve(a.targetId)).id,11);assert.equal((await f.manager.resolve(b.targetId)).id,22);assert.equal((await f.manager.list()).length,2);});
test('service worker reload restores targets but browser session reuse is rejected',async()=>{const f=await fixture();const a=await f.manager.add({tabId:11});const next=new f.TargetManager(f.api);assert.equal((await next.resolve(a.targetId)).id,11);f.session.targetSession='new-browser';await assert.rejects(next.resolve(a.targetId),/SESSION_EXPIRED/);});
test('closed and restricted targets cannot fall back to active tab',async()=>{const f=await fixture();const a=await f.manager.add({tabId:11});f.tabs.delete(11);await assert.rejects(f.manager.resolve(a.targetId),/TAB_CLOSED/);const b=await f.manager.add({tabId:22});f.tabs.get(22).url='chrome://settings';await assert.rejects(f.manager.resolve(b.targetId),/TARGET_RESTRICTED/);});
test('ambiguous URL and unspecified target are rejected',async()=>{const f=await fixture();f.tabs.get(22).url='https://one.test/';await assert.rejects(f.manager.add({url:'https://one.test/'}),/TARGET_AMBIGUOUS/);await assert.rejects(f.manager.add({}),/TARGET_AMBIGUOUS/);});
test('duplicate adds reuse identity and removals do not close browser tabs',async()=>{const f=await fixture();const a=await f.manager.add({tabId:11});assert.equal((await f.manager.add({tabId:11})).targetId,a.targetId);await f.manager.remove(a.targetId);assert.equal(f.tabs.size,2);await assert.rejects(f.manager.get(a.targetId),/TARGET_NOT_FOUND/);});
test('metadata follows navigation and moved windows without retargeting',async()=>{const f=await fixture();const a=await f.manager.add({tabId:11});f.tabs.get(11).url='https://one.test/next';f.tabs.get(11).windowId=3;const state=await f.manager.get(a.targetId);assert.equal(state.windowId,3);assert.equal(state.url,'https://one.test/next');assert.equal(state.contentScriptConnected,null);await f.manager.clear();assert.deepEqual(await f.manager.list(),[]);});
test('extension reload restores epoch but browser startup invalidates old tab IDs',async()=>{const f=await fixture();const a=await f.manager.add({tabId:11});delete f.session.targetSession;const next=new f.TargetManager(f.api);assert.equal((await next.resolve(a.targetId)).id,11);await f.manager.invalidateSession();await assert.rejects(f.manager.resolve(a.targetId),/SESSION_EXPIRED/);});
