(() => {
 document.getElementById('__gptus_use')?.remove();document.getElementById('__gptus_use_theme')?.remove();
 const host=document.createElement('div');host.id='__gptus_use';const shadow=host.attachShadow({mode:'closed'});
 shadow.innerHTML=`<style>:host{position:fixed;right:18px;bottom:90px;z-index:2147483644;font:14px system-ui;color:#e7efff}.shell{width:330px;background:#0c1528f5;border:1px solid #488bff80;border-radius:18px;box-shadow:0 12px 36px #0005;overflow:hidden}.head{display:flex;justify-content:space-between;padding:13px;gap:8px}.body{padding:0 14px 14px;max-height:440px;overflow:auto}.small{font-size:11px;color:#aab9d5}button{background:#1c3560;color:white;border:1px solid #41639b;border-radius:9px;padding:7px;cursor:pointer;font:inherit}label{display:block;margin:9px 0;font-size:12px}textarea{width:100%;box-sizing:border-box;background:#081124;color:white;min-height:70px;border:1px solid #41639b;border-radius:9px;padding:8px;font:16px system-ui}.chip{display:block;text-align:start;width:100%;margin-top:6px;font-size:12px}#status{font-size:12px;margin-top:8px}.hidden{display:none}@media(max-width:600px){:host{right:8px;bottom:78px}.shell{width:min(310px,90vw)}.body{max-height:260px}}</style><div class="shell" dir="rtl"><div class="head"><button id="toggle">✦ ChatGPT Use</button><button id="off" aria-label="إيقاف تخصيص GPT US">×</button></div><div id="body" class="body hidden"><p class="small">تخصيص من إضافة GPT US · حسابك واشتراكك الأصليان</p><button id="refresh">↻ التبويبات</button><div id="tabs"></div><div id="suggestions"></div><textarea id="question" placeholder="ماذا تريد من التبويبات المختارة؟"></textarea><button id="prepare">إرفاق التبويبات في مسودة الشات</button><div id="status" role="status"></div></div></div>`;
 document.documentElement.append(host);const get=id=>shadow.getElementById(id),selected=new Set();
 const style=document.createElement('style');style.id='__gptus_use_theme';style.textContent='html[data-gptus-use="true"] body{background:linear-gradient(140deg,#111a2b,#0d1119)!important}html[data-gptus-use="true"] #prompt-textarea{caret-color:#62b9ff}';document.documentElement.setAttribute('data-gptus-use','true');document.documentElement.append(style);
 function stop(){host.remove();style.remove();document.documentElement.removeAttribute('data-gptus-use');}
 async function send(command,args={}){const response=await chrome.runtime.sendMessage({type:'use_workspace',command,args});if(!response?.ok)throw Error(response?.error||'GPT US unavailable');return response.result;}
 get('toggle').onclick=()=>get('body').classList.toggle('hidden');get('off').onclick=()=>send('use_disable').then(stop);
 async function refresh(){try{const state=await send('use_state');const myTab=await chrome.runtime.sendMessage({type:'use_chat_target'});if(myTab?.targetId)selected.add(myTab.targetId);get('tabs').replaceChildren();get('suggestions').replaceChildren();for(const target of state.targets){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=selected.has(target.targetId);input.disabled=target.status!=='CONNECTED';input.onchange=()=>{if(input.checked)selected.add(target.targetId);else selected.delete(target.targetId);};label.append(input,document.createTextNode(' '+target.title+' · '+target.status));get('tabs').append(label);}for(const item of state.suggestions){for(const text of item.items.slice(0,2)){const button=document.createElement('button');button.className='chip';button.textContent=item.title+' · '+text;button.onclick=()=>{selected.add(item.targetId);get('question').value=text;refresh();};get('suggestions').append(button);}}get('status').textContent='اختر الأهداف ثم جهّز المسودة؛ لا يرسل السؤال تلقائيًا.';}catch(error){get('status').textContent=error.message;}}
 get('refresh').onclick=refresh;
 get('prepare').onclick=async()=>{try{const {prompt}=await send('use_prompt',{targetIds:[...selected],question:get('question').value});const editor=document.querySelector('#prompt-textarea, main [contenteditable="true"][role="textbox"], main [contenteditable="true"]');if(!editor||editor.innerText?.trim()||editor.value?.trim()){get('question').value=prompt;get('status').textContent='المسودة جاهزة هنا؛ احتُفظ بنص الشات الموجود.';return;}editor.focus({preventScroll:true});if(editor.isContentEditable){document.execCommand('insertText',false,prompt);}else{const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;setter?.call(editor,prompt);editor.dispatchEvent(new Event('input',{bubbles:true}));}get('status').textContent='تم تجهيز المسودة. راجعها واضغط إرسال في ChatGPT.';}catch(error){get('status').textContent=error.message;}};
 chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.useEnabled?.newValue===false)stop();});refresh();
})();
