import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import crypto from 'node:crypto';
import {createOwnerOAuth} from './oauth.js';

test('owner OAuth: discovery, manual consent, PKCE, replay, expiry and restart',async()=>{
 let clock=Date.now(),oauth;
 const server=http.createServer(async(req,res)=>{await oauth.handle(req,res,new URL(req.url,issuer));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const issuer=`http://127.0.0.1:${server.address().port}`,secret='synthetic-test-secret-not-a-real-credential';
 oauth=createOwnerOAuth({secret,issuer,now:()=>clock});
 const call=(path,body,headers={})=>fetch(issuer+path,{redirect:'manual',...(body?{method:'POST',body:new URLSearchParams(body),headers:{'content-type':'application/x-www-form-urlencoded',...headers}}:{headers})});
 try{
  assert.equal((await (await call('/.well-known/oauth-protected-resource')).json()).resource,issuer+'/mcp');
  assert.equal((await (await call('/.well-known/oauth-authorization-server')).json()).authorization_response_iss_parameter_supported,true);
  const register=uris=>fetch(issuer+'/oauth/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({redirect_uris:uris,token_endpoint_auth_method:'none'})});
  assert.equal((await register(['https://evil.example/callback'])).status,400);
  const redirect='https://chatgpt.com/connector_platform_oauth_redirect';
  const client=await (await register([redirect])).json();
  oauth=createOwnerOAuth({secret,issuer,now:()=>clock});
  const verifier=crypto.randomBytes(32).toString('base64url');
  const args={client_id:client.client_id,redirect_uri:redirect,response_type:'code',code_challenge_method:'S256',code_challenge:crypto.createHash('sha256').update(verifier).digest('base64url'),resource:issuer+'/mcp',scope:'computer:control',state:'synthetic-state'};
  assert.equal((await call('/oauth/authorize?'+new URLSearchParams({...args,code_challenge_method:'plain'}))).status,400);
  const page=await call('/oauth/authorize?'+new URLSearchParams(args));
  assert.equal(page.status,200);
  assert.equal(page.headers.get('referrer-policy'),'same-origin');
  assert.ok(page.headers.get('content-security-policy').includes("form-action 'self' "+redirect+';'));
  const cookie=page.headers.get('set-cookie').split(';')[0];
  const approvalHtml=await page.text();
  assert.ok(approvalHtml.includes('لمدة 30 يوماً'));
  const request=approvalHtml.match(/name="request" value="([^"]+)"/)[1];
  assert.equal((await call('/oauth/approve',{request,decision:'allow',owner_token:secret},{origin:'null',cookie})).status,400);
  assert.equal((await call('/oauth/approve',{request,decision:'allow',owner_token:secret},{origin:'https://evil.example',cookie})).status,400);
  assert.equal((await call('/oauth/approve',{request,decision:'allow',owner_token:secret},{origin:issuer})).status,400);
  assert.equal((await call('/oauth/approve',{request,decision:'allow',owner_token:'wrong'},{origin:issuer,cookie})).status,403);
  const approved=await call('/oauth/approve',{request,decision:'allow',owner_token:secret},{origin:issuer,cookie});
  assert.equal(approved.status,303);
  const callback=new URL(approved.headers.get('location'));
  assert.equal(callback.searchParams.get('iss'),issuer);
  assert.equal(callback.searchParams.get('state'),args.state);
  const exchange={grant_type:'authorization_code',code:callback.searchParams.get('code'),client_id:client.client_id,redirect_uri:redirect,resource:issuer+'/mcp',code_verifier:verifier};
  const token=await (await call('/oauth/token',exchange)).json();
  assert.equal(token.token_type,'Bearer');
  assert.equal(token.expires_in,30*24*60*60);
  assert.ok(token.refresh_token);
  assert.ok(oauth.accepts('Bearer '+token.access_token));
  assert.equal((await call('/oauth/token',exchange)).status,400);
  assert.equal(oauth.accepts('Bearer '+token.access_token+'tampered'),false);
  assert.equal(createOwnerOAuth({secret,issuer:issuer+'/other'}).accepts('Bearer '+token.access_token),false);
  clock+=3600001;
  assert.equal(oauth.accepts('Bearer '+token.access_token),true);
  assert.equal((await call('/oauth/token',{grant_type:'refresh_token',refresh_token:token.refresh_token,client_id:'wrong',resource:issuer+'/mcp'})).status,400);
  oauth=createOwnerOAuth({secret,issuer,now:()=>clock});
  const renewed=await (await call('/oauth/token',{grant_type:'refresh_token',refresh_token:token.refresh_token,client_id:client.client_id,resource:issuer+'/mcp'})).json();
  assert.ok(oauth.accepts('Bearer '+renewed.access_token));
  clock+=30*24*3600000;
  assert.equal((await call('/oauth/token',{grant_type:'refresh_token',refresh_token:token.refresh_token,client_id:client.client_id,resource:issuer+'/mcp'})).status,400);
  assert.ok(oauth.accepts('Bearer '+secret));
 }finally{await new Promise(resolve=>server.close(resolve));}
});

